stages:
  - trigger-services

trigger-ai:
  stage: trigger-services
  trigger:
    include: cicd_test/AI/.gitlab-ai-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH'  # 브랜치가 있을 때(커밋이 있을 때)
      changes:
        - cicd_test/AI/**/*
      exists:
        - cicd_test/AI/Dockerfile

trigger-be:
  stage: trigger-services
  trigger:
    include: cicd_test/BE/.gitlab-be-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - cicd_test/BE/**/*
      exists:
        - cicd_test/BE/Dockerfile

trigger-fe:
  stage: trigger-services
  trigger:
    include: cicd_test/FE/.gitlab-fe-ci.yml
  rules:
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - cicd_test/FE/**/*
      exists:
        - cicd_test/FE/Dockerfile
